{{- if ne .Values.provider "selfsigned" }}
{{- if eq .Values.provider "aws" }}
{{- if .Values.issuer.dns.enabled }}
{{- if not .Values.aws.route53.secretKey.secretAccessKeySecretRef.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-aws-route53-credentials-secret
  {{- if not (empty .Values.certmanager.namespace) }}
  namespace: {{ .Values.certmanager.namespace }}
  {{- else }}
  namespace: cert-manager
  {{- end}}
type: Opaque
data:
  secret-access-key: {{ .Values.aws.route53.secretKey.secret | b64enc }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}