{{- if eq .Values.provider "selfsigned" }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: issuer-self-signed-{{ .Values.selfsigned.issuerName }}
spec:
  selfSigned: {}
{{- end }}
